/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsDialog.java
 *
 * Created on 04.Oca.2012, 18:29:54
 */
package desktopapplication1;

import org.jdesktop.application.Action;

/**
 *
 * @author kursat
 */
public class SettingsDialog extends javax.swing.JDialog {

    /** Creates new form SettingsDialog */
    public SettingsDialog(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userInfoPanel = new javax.swing.JPanel();
        settings_nameLabel = new javax.swing.JLabel();
        settings_emailLabel = new javax.swing.JLabel();
        settings_passwordLabel = new javax.swing.JLabel();
        settings_nameTextField = new javax.swing.JTextField();
        settings_emailTextField = new javax.swing.JTextField();
        settings_passwordPasswordField = new javax.swing.JPasswordField();
        pathPanel = new javax.swing.JPanel();
        settings_mailsLocationLabel = new javax.swing.JLabel();
        settings_contactsLocationLabel = new javax.swing.JLabel();
        settings_settingsLocationLabel = new javax.swing.JLabel();
        settings_mailsLocationTextField = new javax.swing.JTextField();
        settings_contactsLocationTextField = new javax.swing.JTextField();
        settings_settingsLocationTextField = new javax.swing.JTextField();
        settings_mailsLocationButton = new javax.swing.JButton();
        settings_contactsLocationButton = new javax.swing.JButton();
        settings_settingsLocationButton = new javax.swing.JButton();
        settings_saveSettingsButton = new javax.swing.JButton();
        settings_cancelSettingsButton = new javax.swing.JButton();
        settings_Configurepop3Button = new javax.swing.JButton();
        settings_ConfigureSmtpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(desktopapplication1.DesktopApplication1.class).getContext().getResourceMap(SettingsDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(453, 300));
        setName("Form"); // NOI18N
        setResizable(false);

        userInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("userInfoPanel.border.title"))); // NOI18N
        userInfoPanel.setName("userInfoPanel"); // NOI18N

        settings_nameLabel.setText(resourceMap.getString("settings_nameLabel.text")); // NOI18N
        settings_nameLabel.setName("settings_nameLabel"); // NOI18N

        settings_emailLabel.setText(resourceMap.getString("settings_emailLabel.text")); // NOI18N
        settings_emailLabel.setName("settings_emailLabel"); // NOI18N

        settings_passwordLabel.setText(resourceMap.getString("settings_passwordLabel.text")); // NOI18N
        settings_passwordLabel.setName("settings_passwordLabel"); // NOI18N

        settings_nameTextField.setText(resourceMap.getString("settings_nameTextField.text")); // NOI18N
        settings_nameTextField.setName("settings_nameTextField"); // NOI18N

        settings_emailTextField.setText(resourceMap.getString("settings_emailTextField.text")); // NOI18N
        settings_emailTextField.setName("settings_emailTextField"); // NOI18N

        settings_passwordPasswordField.setText(resourceMap.getString("settings_passwordPasswordField.text")); // NOI18N
        settings_passwordPasswordField.setName("settings_passwordPasswordField"); // NOI18N

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settings_passwordLabel)
                    .addComponent(settings_emailLabel)
                    .addComponent(settings_nameLabel))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settings_nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(settings_emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(settings_passwordPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                .addContainerGap())
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settings_nameLabel)
                    .addComponent(settings_nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settings_emailLabel)
                    .addComponent(settings_emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settings_passwordLabel)
                    .addComponent(settings_passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pathPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pathPanel.border.title"))); // NOI18N
        pathPanel.setName("pathPanel"); // NOI18N

        settings_mailsLocationLabel.setText(resourceMap.getString("settings_mailsLocationLabel.text")); // NOI18N
        settings_mailsLocationLabel.setName("settings_mailsLocationLabel"); // NOI18N

        settings_contactsLocationLabel.setText(resourceMap.getString("settings_contactsLocationLabel.text")); // NOI18N
        settings_contactsLocationLabel.setName("settings_contactsLocationLabel"); // NOI18N

        settings_settingsLocationLabel.setText(resourceMap.getString("settings_settingsLocationLabel.text")); // NOI18N
        settings_settingsLocationLabel.setName("settings_settingsLocationLabel"); // NOI18N

        settings_mailsLocationTextField.setText(resourceMap.getString("settings_mailsLocationTextField.text")); // NOI18N
        settings_mailsLocationTextField.setName("settings_mailsLocationTextField"); // NOI18N

        settings_contactsLocationTextField.setText(resourceMap.getString("settings_contactsLocationTextField.text")); // NOI18N
        settings_contactsLocationTextField.setName("settings_contactsLocationTextField"); // NOI18N

        settings_settingsLocationTextField.setText(resourceMap.getString("settings_settingsLocationTextField.text")); // NOI18N
        settings_settingsLocationTextField.setName("settings_settingsLocationTextField"); // NOI18N

        settings_mailsLocationButton.setText(resourceMap.getString("settings_mailsLocationButton.text")); // NOI18N
        settings_mailsLocationButton.setName("settings_mailsLocationButton"); // NOI18N

        settings_contactsLocationButton.setText(resourceMap.getString("settings_contactsLocationButton.text")); // NOI18N
        settings_contactsLocationButton.setName("settings_contactsLocationButton"); // NOI18N

        settings_settingsLocationButton.setText(resourceMap.getString("settings_settingsLocationButton.text")); // NOI18N
        settings_settingsLocationButton.setName("settings_settingsLocationButton"); // NOI18N

        javax.swing.GroupLayout pathPanelLayout = new javax.swing.GroupLayout(pathPanel);
        pathPanel.setLayout(pathPanelLayout);
        pathPanelLayout.setHorizontalGroup(
            pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pathPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settings_settingsLocationLabel)
                    .addGroup(pathPanelLayout.createSequentialGroup()
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(settings_contactsLocationLabel)
                            .addComponent(settings_mailsLocationLabel))
                        .addGap(18, 18, 18)
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(settings_contactsLocationTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(settings_settingsLocationTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(settings_mailsLocationTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))))
                .addGap(7, 7, 7)
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(settings_contactsLocationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings_settingsLocationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(settings_mailsLocationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pathPanelLayout.setVerticalGroup(
            pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pathPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settings_mailsLocationLabel)
                    .addComponent(settings_mailsLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings_mailsLocationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settings_contactsLocationLabel)
                    .addComponent(settings_contactsLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings_contactsLocationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settings_settingsLocationLabel)
                    .addComponent(settings_settingsLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings_settingsLocationButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        settings_saveSettingsButton.setLabel(resourceMap.getString("settings_saveSettingsButton.label")); // NOI18N
        settings_saveSettingsButton.setName("settings_saveSettingsButton"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(desktopapplication1.DesktopApplication1.class).getContext().getActionMap(SettingsDialog.class, this);
        settings_cancelSettingsButton.setAction(actionMap.get("cancelSettings")); // NOI18N
        settings_cancelSettingsButton.setText(resourceMap.getString("settings_cancelSettingsButton.text")); // NOI18N
        settings_cancelSettingsButton.setName("settings_cancelSettingsButton"); // NOI18N

        settings_Configurepop3Button.setText(resourceMap.getString("settings_Configurepop3Button.text")); // NOI18N
        settings_Configurepop3Button.setName("settings_Configurepop3Button"); // NOI18N

        settings_ConfigureSmtpButton.setText(resourceMap.getString("settings_ConfigureSmtpButton.text")); // NOI18N
        settings_ConfigureSmtpButton.setName("settings_ConfigureSmtpButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pathPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(settings_Configurepop3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(settings_ConfigureSmtpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(settings_cancelSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(settings_saveSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(settings_saveSettingsButton)
                    .addComponent(settings_cancelSettingsButton)
                    .addComponent(settings_Configurepop3Button)
                    .addComponent(settings_ConfigureSmtpButton))
                .addContainerGap())
        );

        settings_cancelSettingsButton.getAccessibleContext().setAccessibleName(resourceMap.getString("cancelSettingsButton.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SettingsDialog dialog = new SettingsDialog(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void cancelSettings() {
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pathPanel;
    private javax.swing.JButton settings_ConfigureSmtpButton;
    private javax.swing.JButton settings_Configurepop3Button;
    private javax.swing.JButton settings_cancelSettingsButton;
    private javax.swing.JButton settings_contactsLocationButton;
    private javax.swing.JLabel settings_contactsLocationLabel;
    private javax.swing.JTextField settings_contactsLocationTextField;
    private javax.swing.JLabel settings_emailLabel;
    private javax.swing.JTextField settings_emailTextField;
    private javax.swing.JButton settings_mailsLocationButton;
    private javax.swing.JLabel settings_mailsLocationLabel;
    private javax.swing.JTextField settings_mailsLocationTextField;
    private javax.swing.JLabel settings_nameLabel;
    private javax.swing.JTextField settings_nameTextField;
    private javax.swing.JLabel settings_passwordLabel;
    private javax.swing.JPasswordField settings_passwordPasswordField;
    private javax.swing.JButton settings_saveSettingsButton;
    private javax.swing.JButton settings_settingsLocationButton;
    private javax.swing.JLabel settings_settingsLocationLabel;
    private javax.swing.JTextField settings_settingsLocationTextField;
    private javax.swing.JPanel userInfoPanel;
    // End of variables declaration//GEN-END:variables
}
