/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsDialog.java
 *
 * Created on 04.Oca.2012, 18:29:54
 */
package desktopapplication1;

import org.jdesktop.application.Action;


import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author kursat
 */
public class SettingsDialog extends javax.swing.JDialog {

    /** Creates new form SettingsDialog */
    public SettingsDialog(java.awt.Frame parent) {
        super(parent);
        initComponents();
        
        nameTextField.setText(DesktopApplication1.config.getName());
        emailTextField.setText(DesktopApplication1.config.getFrom());
        passwordPasswordField.setText(DesktopApplication1.config.getPass());
        
        SMTPHostTextField.setText(DesktopApplication1.config.getSMTPHost());
        SMTPPortTextField.setText(DesktopApplication1.config.getSMTPPort());
        POP3HostTextField.setText(DesktopApplication1.config.getPOP3Host());
        POP3PortTextField.setText(DesktopApplication1.config.getPOP3Port());
        
        mailsLocationTextField.setText(DesktopApplication1.config.getMailsLocation());
        contactsLocationTextField.setText(DesktopApplication1.config.getContactsLocation());
        settingsLocationTextField.setText(DesktopApplication1.config.getFileLocation());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userInfoPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        passwordPasswordField = new javax.swing.JPasswordField();
        pathPanel = new javax.swing.JPanel();
        mailsLocationLabel = new javax.swing.JLabel();
        contactsLocationLabel = new javax.swing.JLabel();
        settingsLocationLabel = new javax.swing.JLabel();
        mailsLocationTextField = new javax.swing.JTextField();
        contactsLocationTextField = new javax.swing.JTextField();
        settingsLocationTextField = new javax.swing.JTextField();
        mailsLocationButton = new javax.swing.JButton();
        contactsLocationButton = new javax.swing.JButton();
        settingsLocationButton = new javax.swing.JButton();
        applySettingsButton = new javax.swing.JButton();
        cancelSettingsButton = new javax.swing.JButton();
        SMTPAndPOP3SettingsPanel = new javax.swing.JPanel();
        SMTPHostLabel = new javax.swing.JLabel();
        SMTPPortLabel = new javax.swing.JLabel();
        POP3HostLabel = new javax.swing.JLabel();
        POP3PortLabel = new javax.swing.JLabel();
        SMTPHostTextField = new javax.swing.JTextField();
        SMTPPortTextField = new javax.swing.JTextField();
        POP3HostTextField = new javax.swing.JTextField();
        POP3PortTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(desktopapplication1.DesktopApplication1.class).getContext().getResourceMap(SettingsDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(453, 438));
        setName("Form"); // NOI18N
        setResizable(false);

        userInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("userInfoPanel.border.title"))); // NOI18N
        userInfoPanel.setName("userInfoPanel"); // NOI18N

        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N

        emailLabel.setText(resourceMap.getString("emailLabel.text")); // NOI18N
        emailLabel.setName("emailLabel"); // NOI18N

        passwordLabel.setText(resourceMap.getString("passwordLabel.text")); // NOI18N
        passwordLabel.setName("passwordLabel"); // NOI18N

        nameTextField.setText(resourceMap.getString("nameTextField.text")); // NOI18N
        nameTextField.setName("nameTextField"); // NOI18N

        emailTextField.setText(resourceMap.getString("emailTextField.text")); // NOI18N
        emailTextField.setName("emailTextField"); // NOI18N

        passwordPasswordField.setText(resourceMap.getString("passwordPasswordField.text")); // NOI18N
        passwordPasswordField.setName("passwordPasswordField"); // NOI18N

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLabel)
                    .addComponent(emailLabel)
                    .addComponent(nameLabel))
                .addGap(18, 62, Short.MAX_VALUE)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nameTextField)
                    .addComponent(emailTextField)
                    .addComponent(passwordPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                .addContainerGap())
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pathPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pathPanel.border.title"))); // NOI18N
        pathPanel.setName("pathPanel"); // NOI18N

        mailsLocationLabel.setText(resourceMap.getString("mailsLocationLabel.text")); // NOI18N
        mailsLocationLabel.setName("mailsLocationLabel"); // NOI18N

        contactsLocationLabel.setText(resourceMap.getString("contactsLocationLabel.text")); // NOI18N
        contactsLocationLabel.setName("contactsLocationLabel"); // NOI18N

        settingsLocationLabel.setText(resourceMap.getString("settingsLocationLabel.text")); // NOI18N
        settingsLocationLabel.setName("settingsLocationLabel"); // NOI18N

        mailsLocationTextField.setText(resourceMap.getString("mailsLocationTextField.text")); // NOI18N
        mailsLocationTextField.setName("mailsLocationTextField"); // NOI18N

        contactsLocationTextField.setText(resourceMap.getString("contactsLocationTextField.text")); // NOI18N
        contactsLocationTextField.setName("contactsLocationTextField"); // NOI18N

        settingsLocationTextField.setText(resourceMap.getString("settingsLocationTextField.text")); // NOI18N
        settingsLocationTextField.setName("settingsLocationTextField"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(desktopapplication1.DesktopApplication1.class).getContext().getActionMap(SettingsDialog.class, this);
        mailsLocationButton.setAction(actionMap.get("onClickMailsLocationButton")); // NOI18N
        mailsLocationButton.setText(resourceMap.getString("mailsLocationButton.text")); // NOI18N
        mailsLocationButton.setName("mailsLocationButton"); // NOI18N

        contactsLocationButton.setAction(actionMap.get("onClickContactsLocationButton")); // NOI18N
        contactsLocationButton.setText(resourceMap.getString("contactsLocationButton.text")); // NOI18N
        contactsLocationButton.setName("contactsLocationButton"); // NOI18N

        settingsLocationButton.setAction(actionMap.get("onClickSettingsLocationButton")); // NOI18N
        settingsLocationButton.setText(resourceMap.getString("settingsLocationButton.text")); // NOI18N
        settingsLocationButton.setName("settingsLocationButton"); // NOI18N

        javax.swing.GroupLayout pathPanelLayout = new javax.swing.GroupLayout(pathPanel);
        pathPanel.setLayout(pathPanelLayout);
        pathPanelLayout.setHorizontalGroup(
            pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pathPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsLocationLabel)
                    .addGroup(pathPanelLayout.createSequentialGroup()
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactsLocationLabel)
                            .addComponent(mailsLocationLabel))
                        .addGap(18, 18, 18)
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contactsLocationTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(settingsLocationTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(mailsLocationTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))))
                .addGap(7, 7, 7)
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(contactsLocationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsLocationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(mailsLocationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pathPanelLayout.setVerticalGroup(
            pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pathPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailsLocationLabel)
                    .addComponent(mailsLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailsLocationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactsLocationLabel)
                    .addComponent(contactsLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactsLocationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsLocationLabel)
                    .addComponent(settingsLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsLocationButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        applySettingsButton.setAction(actionMap.get("onClickApplyButton")); // NOI18N
        applySettingsButton.setText(resourceMap.getString("applySettingsButton.text")); // NOI18N
        applySettingsButton.setName("applySettingsButton"); // NOI18N

        cancelSettingsButton.setAction(actionMap.get("cancelSettings")); // NOI18N
        cancelSettingsButton.setText(resourceMap.getString("cancelSettingsButton.text")); // NOI18N
        cancelSettingsButton.setName("cancelSettingsButton"); // NOI18N

        SMTPAndPOP3SettingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("SMTPAndPOP3SettingsPanel.border.title"))); // NOI18N
        SMTPAndPOP3SettingsPanel.setName("SMTPAndPOP3SettingsPanel"); // NOI18N

        SMTPHostLabel.setText(resourceMap.getString("SMTPHostLabel.text")); // NOI18N
        SMTPHostLabel.setName("SMTPHostLabel"); // NOI18N

        SMTPPortLabel.setText(resourceMap.getString("SMTPPortLabel.text")); // NOI18N
        SMTPPortLabel.setName("SMTPPortLabel"); // NOI18N

        POP3HostLabel.setText(resourceMap.getString("POP3HostLabel.text")); // NOI18N
        POP3HostLabel.setName("POP3HostLabel"); // NOI18N

        POP3PortLabel.setText(resourceMap.getString("POP3PortLabel.text")); // NOI18N
        POP3PortLabel.setName("POP3PortLabel"); // NOI18N

        SMTPHostTextField.setText(resourceMap.getString("SMTPHostTextField.text")); // NOI18N
        SMTPHostTextField.setName("SMTPHostTextField"); // NOI18N

        SMTPPortTextField.setText(resourceMap.getString("SMTPPortTextField.text")); // NOI18N
        SMTPPortTextField.setName("SMTPPortTextField"); // NOI18N

        POP3HostTextField.setText(resourceMap.getString("POP3HostTextField.text")); // NOI18N
        POP3HostTextField.setName("POP3HostTextField"); // NOI18N

        POP3PortTextField.setText(resourceMap.getString("POP3PortTextField.text")); // NOI18N
        POP3PortTextField.setName("POP3PortTextField"); // NOI18N

        javax.swing.GroupLayout SMTPAndPOP3SettingsPanelLayout = new javax.swing.GroupLayout(SMTPAndPOP3SettingsPanel);
        SMTPAndPOP3SettingsPanel.setLayout(SMTPAndPOP3SettingsPanelLayout);
        SMTPAndPOP3SettingsPanelLayout.setHorizontalGroup(
            SMTPAndPOP3SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SMTPAndPOP3SettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SMTPAndPOP3SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SMTPHostLabel)
                    .addComponent(SMTPPortLabel)
                    .addComponent(POP3HostLabel)
                    .addComponent(POP3PortLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(SMTPAndPOP3SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(POP3PortTextField)
                    .addComponent(POP3HostTextField)
                    .addComponent(SMTPPortTextField)
                    .addComponent(SMTPHostTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                .addContainerGap())
        );
        SMTPAndPOP3SettingsPanelLayout.setVerticalGroup(
            SMTPAndPOP3SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SMTPAndPOP3SettingsPanelLayout.createSequentialGroup()
                .addGroup(SMTPAndPOP3SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SMTPHostLabel)
                    .addComponent(SMTPHostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SMTPAndPOP3SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SMTPPortLabel)
                    .addComponent(SMTPPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SMTPAndPOP3SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(POP3HostLabel)
                    .addComponent(POP3HostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SMTPAndPOP3SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(POP3PortLabel)
                    .addComponent(POP3PortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SMTPAndPOP3SettingsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userInfoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pathPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applySettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SMTPAndPOP3SettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(applySettingsButton)
                    .addComponent(cancelSettingsButton))
                .addContainerGap())
        );

        cancelSettingsButton.getAccessibleContext().setAccessibleName(resourceMap.getString("cancelSettingsButton.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SettingsDialog dialog = new SettingsDialog(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void cancelSettings() {
        dispose();
    }

    @Action
    public void onClickApplyButton() {
        DesktopApplication1.config.setFrom(emailTextField.getText());
        DesktopApplication1.config.setPass(passwordPasswordField.getText());
        
        DesktopApplication1.config.setName(nameTextField.getText());
        DesktopApplication1.config.setSMTPHost(SMTPHostTextField.getText());
        DesktopApplication1.config.setSMTPPort(SMTPPortTextField.getText());
        DesktopApplication1.config.setPOP3Host(POP3HostTextField.getText());
        DesktopApplication1.config.setPOP3Port(POP3PortTextField.getText());
        DesktopApplication1.config.setFileLocation(settingsLocationTextField.getText());
        
        DesktopApplication1.config.setMailsLocation(mailsLocationTextField.getText());
        DesktopApplication1.config.setContactsLocation(contactsLocationTextField.getText());
        
        DesktopApplication1.config.writeConfiguration();
        
        dispose();
    }

    @Action
    public void callFileChooser( JTextField textField ) {
            int result;
         
        fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("."));
        fileChooser.setDialogTitle("chooserTitle");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        
        //
        // disable the "All files" option.
        //
        fileChooser.setAcceptAllFileFilterUsed(false);
        //   
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getCurrentDirectory(): "
                +  fileChooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : "
                +  fileChooser.getSelectedFile());
        }
        else {
            System.out.println("No Selection ");
        }
        
        textField.setText(fileChooser.getSelectedFile().getPath());
    }

    @Action
    public void onClickMailsLocationButton() {
        callFileChooser(mailsLocationTextField);
    }

    @Action
    public void onClickContactsLocationButton() {
        callFileChooser(contactsLocationTextField);
    }

    @Action
    public void onClickSettingsLocationButton() {
        callFileChooser(settingsLocationTextField);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel POP3HostLabel;
    private javax.swing.JTextField POP3HostTextField;
    private javax.swing.JLabel POP3PortLabel;
    private javax.swing.JTextField POP3PortTextField;
    private javax.swing.JPanel SMTPAndPOP3SettingsPanel;
    private javax.swing.JLabel SMTPHostLabel;
    private javax.swing.JTextField SMTPHostTextField;
    private javax.swing.JLabel SMTPPortLabel;
    private javax.swing.JTextField SMTPPortTextField;
    private javax.swing.JButton applySettingsButton;
    private javax.swing.JButton cancelSettingsButton;
    private javax.swing.JButton contactsLocationButton;
    private javax.swing.JLabel contactsLocationLabel;
    private javax.swing.JTextField contactsLocationTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton mailsLocationButton;
    private javax.swing.JLabel mailsLocationLabel;
    private javax.swing.JTextField mailsLocationTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JPanel pathPanel;
    private javax.swing.JButton settingsLocationButton;
    private javax.swing.JLabel settingsLocationLabel;
    private javax.swing.JTextField settingsLocationTextField;
    private javax.swing.JPanel userInfoPanel;
    // End of variables declaration//GEN-END:variables

    private javax.swing.JFileChooser fileChooser;
}
