/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bizsoft.emailclient.frontend;

/**
 *
 * @author CodeGuru
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tp_mainTabbedPanel = new javax.swing.JTabbedPane();
        pnl_main = new javax.swing.JPanel();
        sp_mainSplitter = new javax.swing.JSplitPane();
        pnl_contacts = new javax.swing.JPanel();
        pnl_hot = new javax.swing.JPanel();
        sp_hotMailsSplitter = new javax.swing.JSplitPane();
        pnl_mails = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        pnl_filterSettings = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnl_contactsLayout = new javax.swing.GroupLayout(pnl_contacts);
        pnl_contacts.setLayout(pnl_contactsLayout);
        pnl_contactsLayout.setHorizontalGroup(
            pnl_contactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnl_contactsLayout.setVerticalGroup(
            pnl_contactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        sp_mainSplitter.setLeftComponent(pnl_contacts);

        sp_hotMailsSplitter.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout pnl_mailsLayout = new javax.swing.GroupLayout(pnl_mails);
        pnl_mails.setLayout(pnl_mailsLayout);
        pnl_mailsLayout.setHorizontalGroup(
            pnl_mailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        pnl_mailsLayout.setVerticalGroup(
            pnl_mailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mailsLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sp_hotMailsSplitter.setTopComponent(pnl_mails);

        javax.swing.GroupLayout pnl_filterSettingsLayout = new javax.swing.GroupLayout(pnl_filterSettings);
        pnl_filterSettings.setLayout(pnl_filterSettingsLayout);
        pnl_filterSettingsLayout.setHorizontalGroup(
            pnl_filterSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        pnl_filterSettingsLayout.setVerticalGroup(
            pnl_filterSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        sp_hotMailsSplitter.setRightComponent(pnl_filterSettings);

        javax.swing.GroupLayout pnl_hotLayout = new javax.swing.GroupLayout(pnl_hot);
        pnl_hot.setLayout(pnl_hotLayout);
        pnl_hotLayout.setHorizontalGroup(
            pnl_hotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_hotMailsSplitter)
        );
        pnl_hotLayout.setVerticalGroup(
            pnl_hotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_hotMailsSplitter, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        sp_mainSplitter.setRightComponent(pnl_hot);

        javax.swing.GroupLayout pnl_mainLayout = new javax.swing.GroupLayout(pnl_main);
        pnl_main.setLayout(pnl_mainLayout);
        pnl_mainLayout.setHorizontalGroup(
            pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp_mainSplitter)
                .addContainerGap())
        );
        pnl_mainLayout.setVerticalGroup(
            pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp_mainSplitter)
                .addContainerGap())
        );

        tp_mainTabbedPanel.addTab("Home", pnl_main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_mainTabbedPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_mainTabbedPanel)
                .addContainerGap())
        );

        tp_mainTabbedPanel.getAccessibleContext().setAccessibleName("EmailClient");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_contacts;
    private javax.swing.JPanel pnl_filterSettings;
    private javax.swing.JPanel pnl_hot;
    private javax.swing.JPanel pnl_mails;
    private javax.swing.JPanel pnl_main;
    private javax.swing.JSplitPane sp_hotMailsSplitter;
    private javax.swing.JSplitPane sp_mainSplitter;
    private javax.swing.JTabbedPane tp_mainTabbedPanel;
    // End of variables declaration//GEN-END:variables
}
